@host=http://arch.homework

###
GET {{host}}/ping

###
POST {{host}}/user
Content-Type: application/json

{
  "username": "john1doe2",
  "firstName": "John2",
  "lastName": "Doe",
  "email": "bestjohn2@doe.com",
  "phone": "+71002003040"
}

###  
GET {{host}}/user/6
Set-Cookie: session_id=a72c42eb-51ee-40b1-99b8-1826affaccf6; Path=/

### 
GET {{host}}/user/2
X-UserId: 2

###
PUT {{host}}/user/100

{
  "username": "j5891",
  "firstName": "John",
  "lastName": "Doe",
  "email": "bestjohn@doe.com",
  "phone": "+71002003040"
}

###
PUT {{host}}/user/2
Content-Type: application/json

{
  "firstName": "Tom",
  "lastName": "Cat",
  "phone": "+71002003040"
}

###
PUT {{host}}/user/2
Content-Type: application/json
X-UserId: 2

{
  "firstName": "Tom",
  "lastName": "Cat",
  "phone": "+71002003040"
}

###
PUT {{host}}/user/me
Content-Type: application/json
X-UserId: 1

{
  "firstName": "Alice",
  "lastName": "Cat",
  "phone": "+71002003040"
}

###
DELETE {{host}}/user/5

###
GET {{host}}/ping

###
POST {{host}}/user
Content-Type: application/json

{
  "username": "pups",
  "firstName": "lyalya",
  "lastName": "Mimi",
  "email": "mimi@pups.com",
  "phone": "+7100200300"
}

###
POST {{host}}/user
Content-Type: application/json

{
  "username": "cat",
  "firstName": "hello",
  "lastName": "kitty",
  "email": "hello@pups.com",
  "phone": "+7100200305"
}
