apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-dp
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: hw7kuber
          image: kisuni/hw7kuber
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: users-configmap
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: users-configmap
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: users-configmap
                  key: DB_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: DB_PASSWORD
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres
